### ISSUE TITLE
Check if i have set the permissions for oscar to update these issues 

### ISSUE THREAD

**Issue by timm** [timm/changeware#13]
oscar,
 please try to edit this comment and close issue. ping me if failure.

Edit by Oscar

**Comment by ojcchar** [comment]
Done

On Sun, Aug 9, 2015 at 6:28 PM, Tim Menzies notifications@github.com
wrote:

> Assigned #13 https://github.com/timm/changeware/issues/13 to @ojcchar
> https://github.com/ojcchar.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/timm/changeware/issues/13#event-377504225.

## 

Oscar Chaparro
